ChrisDemo/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ChrisDemo.Models
{
    [Table("Order")]
    public class Order
    {
        public Order()
        {
            OrderItems = new HashSet<OrderItem>();
        }

        public int Id { get; set; }

        [Display(Name = "Location")]
        public int LocationId { get; set; }

        [Required]
        public DateTime Date { get; set; }

        public int? CustomerId { get; set; }

        public virtual Customer Customer { get; set; }

        public virtual ICollection<OrderItem> OrderItems { get; set; }

        public virtual Location Location { get; set; }
    }
}

ChrisDemo/Controllers/ItemController.cs
using ChrisDemo.Models;
using ChrisDemo.ViewModel.Item;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ChrisDemo.Controllers
{
    public class ItemController : Controller
    {
        private ChrisDemoContext db;

        public ItemController()
        {
            db = new ChrisDemoContext();
        }

        // GET: Item/Index
        public ActionResult Index()
        {
            // Try to get a list of Items
            try
            {
                return View(new IndexViewModel
                {
                    Items = db.Item.ToList()
                });               
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }
           
        }

        // GET: Item/Create
        public ActionResult Create()
        {
           // Try to retrieve properties needed to create a new Item        
            try
            {
                return View(new CreateViewModel
                {
                    Item = new Item(),
                    Categories = db.Category.ToList(),
                    Locations = db.Location.ToList(),
                    SelectedLocationIds = new List<int>()                    
                });
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

        // POST: Item/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateViewModel viewModel)
        {
            // Try to save a new Item
            try
            {
                if (ModelState.IsValid)
                {
                    // Loop through Location Id's to save an Item's Locations from the multi select list
                    if(viewModel.SelectedLocationIds != null)
                    {
                        foreach (var sli in viewModel.SelectedLocationIds)
                        {
                            Location location = db.Location.Single(l => l.Id == sli);
                            viewModel.Item.Locations.Add(location);
                        }
                    }
                    
                    // Add Item to db
                    db.Item.Add(viewModel.Item);

                    // Save to the db
                    db.SaveChanges();

                    // Message to handle Create's result
                    TempData["success"] = "Item was successfully created";

                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                // Message to handle Create's result
                TempData["danger"] = "Item was not created";

                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        // GET: Item/Details/id
        public ActionResult Details(int id)
        {
            // Try to get details of User's selected Item
            try
            {               
                return View(new DetailsViewModel
                {
                    Item = db.Item.Single(i => i.Id == id)
                });
            }
            catch (InvalidOperationException)
            {
                // Message to handle Details's result
                TempData["danger"] = "Item does not exist";

                return RedirectToAction("Index");
            }  
            catch (Exception)
            {
                // Message to handle Detail's result
                TempData["danger"] = "Item does not exist";

                return RedirectToAction("Index");
            }
        }

        // GET: Item/Edit/id
        public ActionResult Edit(int id)
        {
            // Try to Edit the user's selected Item
            try
            {
                // Get the item by finding the id
                var item = db.Item.Single(l => l.Id == id);

                return View(new EditViewModel
                {
                    Item = item,
                    Categories = db.Category.ToList(),
                    Locations = db.Location.ToList(),
                    SelectedLocationIds = item.Locations.Select(e => e.Id).ToList()
                });
            }
            catch (Exception)
            {
                // Message to handle Edit's result
                TempData["danger"] = "Item does not exist";

                return RedirectToAction("Index");
            }
        }

        // POST: Item/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditViewModel viewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Finds the item by id
                    var item = db.Item.Single(i => i.Id == viewModel.Item.Id);

                    // Set the item's properties to the user's values
                    item.Description = viewModel.Item.Description;
                    item.ItemNumber = viewModel.Item.ItemNumber;
                    
                    // Related Tables
                    item.CategoryId = viewModel.Item.CategoryId;

                    // Remove all Items from the Location
                    foreach (var l in item.Locations.ToList())
                    {
                        item.Locations.Remove(l);
                    }

                    // Set Item's new location to from the user's choices on the multi select list
                    if(viewModel.SelectedLocationIds != null)
                    {
                        foreach (var sii in viewModel.SelectedLocationIds)
                        {
                            var location = db.Location.Single(i => i.Id == sii);
                            item.Locations.Add(location);
                        }
                    }
                    
                    // Save changes to db
                    db.SaveChanges();

                    // Message to handle Edit's result
                    TempData["success"] = "Item updated successfully";

                    return RedirectToAction("Index");
                }

                return View(viewModel);
            }
            catch (Exception)
            {
                // Message to handle Edit's result
                TempData["danger"] = "Item was not updated";

                return View(viewModel);
            }
        }


        // GET: Item/Delete/id
        public ActionResult Delete(int id)
        {
            // Try to Delete the user's selected record
            try
            {
                return View(new DeleteViewModel
                {
                    Item = db.Item.Single(i => i.Id == id)
                });
            }
            catch (Exception)
            {
                // Message to handle Delete's result
                TempData["danger"] = "Item does not exist";

                return RedirectToAction("Index");
            }
        }

        // POST: Item/Delete/id
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            // Try to delete user's selected record on button click
            try
            {                
                var item = db.Item.Single(i => i.Id == id);
                db.Item.Remove(item);
                db.SaveChanges();

                // Message to handle Delete's result
                TempData["success"] = "Item was deleted successfully";

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                // Message to handle Delete's result
                TempData["danger"] = "Item was not deleted";

                return RedirectToAction("Delete");
            }
        }

        // Dispose method
        // closes the db connection
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }        
    }
}

ChrisDemo/Views/Order/Create.cshtml
@model ChrisDemo.ViewModel.Order.CreateViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />

        <div class="form-group">
            @Html.Label("Location", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Order.LocationId, new MultiSelectList(Model.Locations, "Id", "Name"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Order.LocationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Customer", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Order.CustomerId, new MultiSelectList(Model.Customers, "Id", "Name"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Order.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Order.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Order.Date, "", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order.Date, "", new { @class = "text-danger" })
            </div>
        </div>  

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ChrisDemo/Views/Order/CreateItem.cshtml
@model ChrisDemo.ViewModel.Order.CreateItemViewModel
@{
    ViewBag.Title = "OrderItemCreate";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Item</h4>
        <hr />

        @Html.HiddenFor(model => model.OrderItem.OrderId)

        <div class="form-group">
            @Html.Label("Item Number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdOrItemNumber, "", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderItem.ItemId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderItem.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderItem.Price, "", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderItem.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="create" class="btn btn-default"  />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ChrisDemo/Views/Order/Delete.cshtml
@model ChrisDemo.ViewModel.Order.DeleteViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Order.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Order.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Order.Customer.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Order.Customer.Name)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ChrisDemo/Views/Order/DeleteOrderItem.cshtml
@model ChrisDemo.ViewModel.Order.DeleteViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>

<div>
    <h4>Order Item</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderItem.ItemId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderItem.ItemId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderItem.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderItem.Price)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ChrisDemo/Views/Order/Details.cshtml
@model ChrisDemo.ViewModel.Order.DetailsViewModel
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Order</h4>
    <hr />
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Order.Id)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Order.Date)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Order.Location)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Order.Customer.Name)
                </th>

                <th></th>
            </tr>
        </thead>

        <tr>
            <td>
                @Html.DisplayFor(model => model.Order.Id)
            </td>

            <td>
                @Html.DisplayFor(model => model.Order.Date)
            </td>

            <td>
                @Html.ActionLink(Model.Order.Location.Name, "Details", "Location", new { id = Model.Order.LocationId }, null)
            </td>


            @if (Model.Order.Customer != null)
            {
                <td>
                    @Html.ActionLink(Model.Order.Customer.Name, "Details", "Customer", new { id = Model.Order.CustomerId }, null)
                </td>
            }
            else
            {
                <td></td>
            }         
           
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = Model.Order.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = Model.Order.Id }) |
                @Html.ActionLink("Back to List", "Index")
            </td>
        </tr>        
    </table>

    @*
        Create a table
        Assign table header statically
        Loop over the OrderItems
        Display a table row for each
    *@

    <table class="table">
        <thead>
            <tr>
                <th>
                    Item Number
                </th>
                <th>
                    Price
                </th>
                <th></th>
            </tr>
        </thead>
        

        @foreach(var oi in Model.Order.OrderItems)
        {
            <tr>
               
                <td>
                    @Html.ActionLink(oi.Item.ItemNumber, "Details", "Item", new { id = oi.ItemId.ToString() }, null) <br /><br />
                </td>
                <td>
                    @oi.Price.ToString()
                </td>
                <td>
                    @Html.ActionLink("Edit", "EditItem", new { id = oi.Id }) |
                    @Html.ActionLink("Delete", "DeleteOrderItem", new { id = oi.Id }) |
                </td>
            </tr>
        }       
    </table>

    @Html.ActionLink("Add Item", "CreateItem", new { id = Model.Order.Id })

</div>

ChrisDemo/Views/Order/Edit.cshtml
@model ChrisDemo.ViewModel.Order.EditViewModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Order.Id)
        
        <div class="form-group">
            @Html.LabelFor(model => model.Order.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Order.LocationId, new MultiSelectList(Model.Locations, "Id", "Name"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Order.LocationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Customer", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Order.CustomerId, new MultiSelectList(Model.Customers, "Id", "Name"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Order.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Order.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Order.Date, "", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order.Date, "", new { @class = "text-danger" })
            </div>
        </div>        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class = "btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ChrisDemo/Views/Order/EditItem.cshtml
@model ChrisDemo.ViewModel.Order.EditItemViewModel
@{
    ViewBag.Title = "EditItem";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Item</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OrderItem.Id)
                
        <div class="form-group">
            @Html.LabelFor(model => model.OrderItem.ItemId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderItem.ItemId, "", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderItem.ItemId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderItem.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderItem.Price, "", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderItem.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ChrisDemo/Views/Order/Index.cshtml
@model ChrisDemo.ViewModel.Order.IndexViewModel

@{
    ViewBag.Title = "Order";
}

<h2>Order</h2>

<p>
    @Html.ActionLink("Create New", "Create")
<p>

<table class="table">
    <thead>
        <tr>
            <th>
                Order Id
            </th>
            <th>
                Date
            </th>
            <th>
                Location
            </th>
            <th>
                Customer
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var order in Model.Orders)
        {
            <tr>
                <td>
                    @order.Id
                </td>
                <td>
                    @order.Date
                </td>
                <td>
                    @order.Location.Name
                </td>

                @if (order.Customer != null)
                {
                    <td>
                        @Html.ActionLink(order.Customer.Name, "Details", "Customer", new { id = order.CustomerId }, null)
                    </td>
                }
                else
                {
                    <td></td>
                }
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = order.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = order.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = order.Id }) |
                </td>
            </tr>
        }
    </tbody>
</table>